version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./docker-dev.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    tty: true

  # TODO: ASP Backend

  postgres:
    image: postgres:12.3-alpine
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: postgresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dependencies:

networks:
  dev:
    driver: bridge
# server connection-string jdbc:postgresql://localhost:5433/databasename
